'use client';

import { Player } from '@remotion/player';
import { AbsoluteFill, interpolate, spring, useCurrentFrame, useVideoConfig } from 'remotion';
import { Check, CursorClick, QrCode, Sparkle, UserPlus } from '@phosphor-icons/react';

function ProductDemoComposition() {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const entrance = spring({ frame, fps, config: { damping: 18, stiffness: 90 } });
  const step = Math.min(2, Math.floor((frame % 270) / 90));
  const local = frame % 90;
  const scan = interpolate(local, [10, 72], [15, 220], { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' });
  const items = ['Lia Sample', 'Full-stack developer', 'https://example.com/lia'];
  return (
    <AbsoluteFill style={{ background: 'linear-gradient(140deg,#25040f,#670D2F 65%,#A53860)', color: '#fff', fontFamily: 'var(--font-manrope)', padding: 34 }}>
      <div style={{ opacity: .18, position: 'absolute', inset: 0, backgroundImage: 'linear-gradient(#fff 1px,transparent 1px),linear-gradient(90deg,#fff 1px,transparent 1px)', backgroundSize: '44px 44px' }} />
      <div style={{ position: 'relative', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, fontSize: 13, fontWeight: 800 }}><Sparkle weight="fill" color="#EF88AD" /> CRETO / PRODUCT TOUR</div>
        <div style={{ display: 'flex', gap: 7 }}>{['Account','Build','Share'].map((label,index)=><span key={label} style={{ borderRadius: 999, padding: '7px 11px', fontSize: 10, fontWeight: 800, background: index === step ? '#EF88AD' : 'rgba(255,255,255,.09)', color: index === step ? '#3A0519' : 'rgba(255,255,255,.6)' }}>{index < step ? '✓ ' : ''}{label}</span>)}</div>
      </div>
      <div style={{ position:'relative', flex:1, display:'grid', placeItems:'center', transform:`scale(${.94 + entrance * .06})`, opacity: entrance }}>
        {step === 0 && <div style={{ width:'76%', display:'grid', gridTemplateColumns:'1fr 1fr', borderRadius:28, overflow:'hidden', background:'#fffafc', color:'#3A0519', boxShadow:'0 30px 80px rgba(0,0,0,.28)' }}><div style={{ padding:36, background:'#EF88AD22', display:'grid', placeItems:'center' }}><div style={{ width:130,height:130,borderRadius:40,background:'#670D2F',display:'grid',placeItems:'center' }}><UserPlus size={60} color="#EF88AD" weight="duotone"/></div></div><div style={{ padding:35 }}><b style={{ fontSize:24,fontFamily:'var(--font-cormorant)' }}>Start with your hello.</b><p style={{ marginTop:8,fontSize:12,color:'#815b69' }}>Sample data — no account is created.</p><div style={{ marginTop:22,display:'grid',gap:9 }}>{['lia@example.com','••••••••••'].map((value,index)=><div key={value} style={{ height:38,border:'1px solid #ecd2dc',borderRadius:10,padding:'11px 13px',fontSize:10,color:index?'#A53860':'#6f4e5b' }}>{value.slice(0,Math.ceil(local/9))}</div>)}</div><div style={{ marginTop:13,height:38,borderRadius:10,background:'#670D2F',display:'grid',placeItems:'center',color:'#fff',fontSize:10,fontWeight:800 }}>Preview account</div></div></div>}
        {step === 1 && <div style={{ width:'88%',display:'grid',gridTemplateColumns:'1.12fr .88fr',gap:18 }}><div style={{ borderRadius:24,background:'#fffafc',padding:24,color:'#3A0519',boxShadow:'0 24px 70px rgba(0,0,0,.24)' }}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between'}}><b style={{fontFamily:'var(--font-cormorant)',fontSize:23}}>Build a sample profile</b><CursorClick color="#A53860"/></div><div style={{marginTop:18,display:'grid',gap:9}}>{items.map((item,index)=><div key={item} style={{border:'1px solid #ecd2dc',borderRadius:11,padding:'11px 13px',fontSize:10,color:'#714959'}}>{local > index*15 ? item.slice(0,Math.ceil((local-index*15)/3)) : ''}</div>)}</div><div style={{marginTop:18,display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:8}}>{['Minimal','Glass','Rose','Neon'].map((name,index)=><div key={name} style={{height:58,borderRadius:12,border:index===Math.floor(local/22)%4?'2px solid #A53860':'1px solid #ecd2dc',background:['#fff','#670D2F','#EF88AD','#16020a'][index],display:'grid',placeItems:'end center',padding:5,color:index===0?'#3A0519':'#fff',fontSize:7}}>{name}</div>)}</div></div><div style={{borderRadius:24,background:['#fff','#670D2F','#fce8ef','#130108'][Math.floor(local/22)%4],padding:28,color:Math.floor(local/22)%4===0?'#3A0519':'#fff',display:'flex',flexDirection:'column',alignItems:'center',textAlign:'center',transition:'none',boxShadow:'0 24px 70px rgba(0,0,0,.25)'}}><div style={{width:70,height:70,borderRadius:25,background:'#EF88AD',border:'4px solid #A53860'}}/><b style={{marginTop:18,fontFamily:'var(--font-cormorant)',fontSize:26}}>Lia Sample</b><p style={{fontSize:9,opacity:.65}}>Full-stack developer</p><div style={{marginTop:18,display:'flex',gap:7}}>{[0,1,2].map(i=><span key={i} style={{width:28,height:28,borderRadius:10,border:'1px solid currentColor',opacity:.5}}/>)}</div></div></div>}
        {step === 2 && <div style={{width:'78%',display:'grid',gridTemplateColumns:'1fr 1fr',alignItems:'center',gap:40}}><div style={{position:'relative',width:250,height:250,borderRadius:28,background:'#fff',padding:22,boxShadow:'0 28px 80px rgba(0,0,0,.3)'}}><QrCode size={206} color="#3A0519" weight="thin"/><div style={{position:'absolute',left:18,right:18,top:scan,height:3,background:'#EF88AD',boxShadow:'0 0 22px #EF88AD'}}/></div><div><p style={{fontSize:11,fontWeight:800,color:'#EF88AD',letterSpacing:2}}>SAMPLE QR PREVIEW</p><h2 style={{marginTop:12,fontFamily:'var(--font-cormorant)',fontSize:45,lineHeight:.9}}>A sample profile appears.</h2><div style={{marginTop:22,border:'1px solid rgba(255,255,255,.18)',borderRadius:18,padding:16,background:'rgba(255,255,255,.08)',transform:`translateY(${interpolate(local,[30,70],[20,0],{extrapolateLeft:'clamp',extrapolateRight:'clamp'})}px)`,opacity:interpolate(local,[25,55],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'})}}><div style={{display:'flex',gap:12,alignItems:'center'}}><span style={{width:42,height:42,borderRadius:14,background:'#EF88AD'}}/><span><b style={{fontSize:12}}>Lia Sample</b><small style={{display:'block',opacity:.5,fontSize:8}}>example.com/lia-profile</small></span><Check style={{marginLeft:'auto'}}/></div></div></div></div>}
      </div>
      <p style={{ position:'relative', textAlign:'center', fontSize:10, opacity:.55 }}>Create an account → make it yours → share one lasting QR</p>
    </AbsoluteFill>
  );
}

export function ProductDemo() {
  return <div className="overflow-hidden rounded-[2rem] border border-[#EF88AD]/25 bg-[#3A0519] shadow-[0_35px_100px_rgba(58,5,25,.24)]"><Player acknowledgeRemotionLicense component={ProductDemoComposition} durationInFrames={270} compositionWidth={800} compositionHeight={500} fps={30} loop autoPlay controls={false} style={{ width:'100%', aspectRatio:'8 / 5' }} /></div>;
}
